server:
  port: 443
#  port: 8080
  servlet:
    context-path: /wxvideo
    session:
      timeout: 1800
  ssl:
    key-store: classpath:2373213_www.wenchuangshixuan.com.pfx
    key-store-password: 442wThb6
    keyStoreType: PKCS12
      
spring: 
  application: 
    name: wxvideo
  
  servlet:
    multipart:
       enabled: true
       max-file-size: 20MB
       max-request-size: 200MB
    
  session:
    store-type: REDIS
    redis:
      namespace: spring:session
  
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wxvideo?useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: root
#    password: 123456
#    password: Admin@123
#    password: root
    password: wcsx@#$123456
    
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 100
    filters: stat
    
    redis:
        host: localhost
        port: 6379
        
      
mybatis: 
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.wx.video.entity

#pagehelper:
#  helper-dialect: mysql
#  reasonable: true
#  support-methods-arguments: true
#  params: count=countSql 
  
logging:
  level:
     com.wx.video.dao: debug
     
auth: 
  enable: true
  exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,*.html,/webjars*,/admin/login"
  cors-origin: http://localhost:8080
  jwtKey: 'jiguiquan'
  timeout: 1800
  
upload: 
#  basePath: E:\nginx\html\upload
#  urlPrefix: http://192.168.0.105/upload/
  basePath: F:\nginx\html\upload
  urlPrefix: http://172.16.10.84/upload/
  